name: GitHub Pages Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - release

jobs:
  deploy:
    name: Build and deploy time-keeper
    runs-on: ubuntu-22.04

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      contents: read
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: cp -r src/ public/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './public'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
